version: "2"
services:
  web:
    image: apache-node-server
    links:
      - db
    ports:
      - "8000:80"
      - "8001:8089"
      - "8002:8090"
    volumes:
      - .:/var/www/html
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root