# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    simulator:
        class: AppBundle\Service\Simulator
        arguments: [%frais_notaire_pourcent%, %assurance_pno_pourcent%, %assurance_grl_pourcent%, %assurance_credit%, %ammortissemnt_bien%, %ammortissemnt_meuble%]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
